# Generated by Django 5.2.13 on 2026-05-01 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='content_type',
            field=models.CharField(choices=[('text', '텍스트'), ('image', '이미지'), ('file', '첨부파일'), ('mixed', '혼합'), ('unknown', '알 수 없음')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ContestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contests.contest')),
            ],
        ),
        migrations.CreateModel(
            name='CosntestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('hwp', 'HWP'), ('hwpx', 'HWPX'), ('doc', 'DOC'), ('docx', 'DOCX'), ('zip', 'ZIP'), ('etc', 'ETC')], default='etc', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contests.contest')),
            ],
        ),
    ]
