# Generated by Django 5.2.13 on 2026-05-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_content_type_contest_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CosntestAttachment',
            new_name='ContestAttachment',
        ),
        migrations.AlterField(
            model_name='contest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
