# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contests", "0003_rename_cosntestattachment_contestattachment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contest",
            old_name="region",
            new_name="host_region",
        ),
        migrations.AddField(
            model_name="contest",
            name="organizer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contest",
            name="total_prize",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contest",
            name="first_prize",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
